apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: mud
build:
  local:
    push: false
  artifacts:
    - image: zrma/mud/api
      context: .
      docker:
        dockerfile: docker/api.Dockerfile
    - image: rabbitmqoperator/cluster-operator
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: zrma/mud/worker
      context: .
      docker:
        dockerfile: docker/worker.Dockerfile
manifests:
  rawYaml:
    - k8s/namespace.mud.yaml
    - k8s/namespace.yaml
    - k8s/rabbitmq-cluster-operator.yml
    - k8s/rabbitmq.read.role.yaml
    - k8s/rabbitmq.role.bind.yaml
    - k8s/rabbitmq.service.yaml
    - kubernetes-manifests/api.deployment.yaml
    - kubernetes-manifests/api.service.yaml
    - kubernetes-manifests/worker.deployment.yaml
