# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    sha256: { }
  artifacts:
    - context: .
      image: api
      docker:
        dockerfile: docker/api.Dockerfile
        noCache: false
        squash: false
    - context: .
      image: worker
      docker:
        dockerfile: docker/worker.Dockerfile
        noCache: false
        squash: false
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/**
profiles:
  - name: cloudbuild
    build:
      googleCloudBuild: { }
