apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mud
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      namespace: mud
      app: api
  template:
    metadata:
      labels:
        namespace: mud
        app: api
    spec:
      containers:
        - name: server
          image: api
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
