apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mud
  name: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      namespace: mud
      app: worker
      tier: backend
  template:
    metadata:
      labels:
        namespace: mud
        app: worker
        tier: backend
    spec:
      containers:
        - name: server
          image: worker
