apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
      tier: backend
  template:
    metadata:
      labels:
        app: worker
        tier: backend
    spec:
      containers:
        - name: server
          image: worker
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
