// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: mud.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_NORTH Direction = 0
	Direction_SOUTH Direction = 1
	Direction_EAST  Direction = 2
	Direction_WEST  Direction = 3
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "NORTH",
		1: "SOUTH",
		2: "EAST",
		3: "WEST",
	}
	Direction_value = map[string]int32{
		"NORTH": 0,
		"SOUTH": 1,
		"EAST":  2,
		"WEST":  3,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_mud_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_mud_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_mud_proto_rawDescGZIP(), []int{0}
}

type MoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player    string    `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Direction Direction `protobuf:"varint,2,opt,name=direction,proto3,enum=Direction" json:"direction,omitempty"`
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mud_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mud_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_mud_proto_rawDescGZIP(), []int{0}
}

func (x *MoveRequest) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *MoveRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_NORTH
}

type MoveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player string `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Ok     bool   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Err    string `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *MoveReply) Reset() {
	*x = MoveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mud_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveReply) ProtoMessage() {}

func (x *MoveReply) ProtoReflect() protoreflect.Message {
	mi := &file_mud_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveReply.ProtoReflect.Descriptor instead.
func (*MoveReply) Descriptor() ([]byte, []int) {
	return file_mud_proto_rawDescGZIP(), []int{1}
}

func (x *MoveReply) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *MoveReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MoveReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_mud_proto protoreflect.FileDescriptor

var file_mud_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x0b, 0x4d,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x12, 0x28, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x45, 0x0a, 0x09,
	0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x65, 0x72, 0x72, 0x2a, 0x35, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x09, 0x0a, 0x05, 0x4e, 0x4f, 0x52, 0x54, 0x48, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53,
	0x4f, 0x55, 0x54, 0x48, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x41, 0x53, 0x54, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x57, 0x45, 0x53, 0x54, 0x10, 0x03, 0x32, 0x29, 0x0a, 0x03, 0x4d, 0x75,
	0x64, 0x12, 0x22, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0c, 0x2e, 0x4d, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mud_proto_rawDescOnce sync.Once
	file_mud_proto_rawDescData = file_mud_proto_rawDesc
)

func file_mud_proto_rawDescGZIP() []byte {
	file_mud_proto_rawDescOnce.Do(func() {
		file_mud_proto_rawDescData = protoimpl.X.CompressGZIP(file_mud_proto_rawDescData)
	})
	return file_mud_proto_rawDescData
}

var file_mud_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mud_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mud_proto_goTypes = []interface{}{
	(Direction)(0),      // 0: Direction
	(*MoveRequest)(nil), // 1: MoveRequest
	(*MoveReply)(nil),   // 2: MoveReply
}
var file_mud_proto_depIdxs = []int32{
	0, // 0: MoveRequest.direction:type_name -> Direction
	1, // 1: Mud.Move:input_type -> MoveRequest
	2, // 2: Mud.Move:output_type -> MoveReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mud_proto_init() }
func file_mud_proto_init() {
	if File_mud_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mud_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mud_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mud_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mud_proto_goTypes,
		DependencyIndexes: file_mud_proto_depIdxs,
		EnumInfos:         file_mud_proto_enumTypes,
		MessageInfos:      file_mud_proto_msgTypes,
	}.Build()
	File_mud_proto = out.File
	file_mud_proto_rawDesc = nil
	file_mud_proto_goTypes = nil
	file_mud_proto_depIdxs = nil
}
