// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.2
// source: mud.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Mud_Move_FullMethodName = "/Mud/Move"
)

// MudClient is the client API for Mud service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MudClient interface {
	Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveReply, error)
}

type mudClient struct {
	cc grpc.ClientConnInterface
}

func NewMudClient(cc grpc.ClientConnInterface) MudClient {
	return &mudClient{cc}
}

func (c *mudClient) Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveReply, error) {
	out := new(MoveReply)
	err := c.cc.Invoke(ctx, Mud_Move_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MudServer is the server API for Mud service.
// All implementations must embed UnimplementedMudServer
// for forward compatibility
type MudServer interface {
	Move(context.Context, *MoveRequest) (*MoveReply, error)
	mustEmbedUnimplementedMudServer()
}

// UnimplementedMudServer must be embedded to have forward compatible implementations.
type UnimplementedMudServer struct {
}

func (UnimplementedMudServer) Move(context.Context, *MoveRequest) (*MoveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Move not implemented")
}
func (UnimplementedMudServer) mustEmbedUnimplementedMudServer() {}

// UnsafeMudServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MudServer will
// result in compilation errors.
type UnsafeMudServer interface {
	mustEmbedUnimplementedMudServer()
}

func RegisterMudServer(s grpc.ServiceRegistrar, srv MudServer) {
	s.RegisterService(&Mud_ServiceDesc, srv)
}

func _Mud_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MudServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mud_Move_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MudServer).Move(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mud_ServiceDesc is the grpc.ServiceDesc for Mud service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mud_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Mud",
	HandlerType: (*MudServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Move",
			Handler:    _Mud_Move_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mud.proto",
}
